---
- name: Converge
  hosts: all

  vars:
    swag__home: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') }}/.molecule/swag"
    swag__port_http: 9080
    swag__port_https: 9443
    swag__remove_existing_container: false
    swag__remove_existing_home_dir: false
    swag__pull_image: false
    swag__url: localhost

  pre_tasks:
    - name: Ensure keys directory exists
      ansible.builtin.file:
        path: "{{ swag__home }}/config/keys"
        state: directory
        mode: "0755"

    - name: Generate self-signed certificate
      ansible.builtin.command: >
        openssl req -x509 -nodes -days 365 -newkey rsa:2048
        -keyout "{{ swag__home }}/config/keys/cert.key"
        -out "{{ swag__home }}/config/keys/cert.crt"
        -subj "/C=US/ST=Test/L=Test/O=Test/CN=localhost"
      args:
        creates: "{{ swag__home }}/config/keys/cert.crt"

    - name: Update apt cache
      apt: update_cache=yes cache_valid_time=600
      when: ansible_facts.os_family == 'Debian'
      changed_when: false

  roles:
    - role: bsmeding.swag_docker
