---
- name: Converge SWAG Docker
  hosts: all
  become: true
  vars:
    swag__url: "swag.local"
    swag__email: "test@example.com"
    docker_service_manage: true
  pre_tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 600
      when: ansible_os_family == 'Debian'

    - name: Wait for systemd to complete initialization
      ansible.builtin.command: systemctl is-system-running
      register: systemctl_status
      until: >
        'running' in systemctl_status.stdout or
        'degraded' in systemctl_status.stdout
      retries: 30
      delay: 5
      when: ansible_service_mgr == 'systemd'
      changed_when: false
      failed_when: systemctl_status.rc > 1

    - name: Check if Docker socket exists
      stat:
        path: /var/run/docker.sock
      register: docker_socket

    - name: Ensure Docker socket permissions are correct
      file:
        path: /var/run/docker.sock
        mode: '0666'
      when: docker_socket.stat.exists

    - name: Start Docker service manually if needed
      ansible.builtin.service:
        name: docker
        state: started
        enabled: true
      when: 
        - ansible_service_mgr == 'systemd'
        - docker_socket.stat.exists
      ignore_errors: true

    - name: Wait for Docker service to be ready
      ansible.builtin.wait_for:
        path: /var/run/docker.sock
        timeout: 60
      when: docker_socket.stat.exists

  roles:
    - role: bsmeding.docker
      when: docker_socket.stat.exists
    - role: bsmeding.swag_docker
