---
- name: Converge
  hosts: all

  vars:
    swag__home: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') }}/.molecule/swag"
    swag__port_http: 9080
    swag__port_https: 9443
    swag__remove_existing_container: false
    swag__remove_existing_home_dir: false

  pre_tasks:
    - name: Ensure Molecule directories exist
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: "0777"
      loop:
        - "{{ swag__home }}/config"
        - "{{ swag__home }}/www"

    - name: Update apt cache
      apt: update_cache=yes cache_valid_time=600
      when: ansible_facts.os_family == 'Debian'
      changed_when: false

  roles:
    - role: bsmeding.swag_docker
