---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: "bsmeding/ansible_cicd_ubuntu2204"
    command: ""
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
