---
- name: Prepare test instance
  hosts: all
  become: true
  tasks:
    - name: Install pip
      apt:
        name: python3-pip
        state: present

    - name: Install Python requests module
      pip:
        name: requests 