---
- name: Verify SWAG Docker role
  hosts: all
  become: true
  vars_files:
    - ../../defaults/main.yml
  tasks:
    - name: Set molecule testing overrides
      ansible.builtin.set_fact:
        swag__home: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') }}/.molecule/swag"
        molecule_tmp_dir: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') }}/.molecule/ansible-tmp"
        swag__port_http: 9080
        swag__port_https: 9443
        swag__directory_volumes:
          - "{{ swag__home }}/config:/config"
          - "{{ swag__home }}/www:/var/www"
        swag__file_volumes: []
        swag__extra_env:
          CURL_HTTP_PORT: "{{ swag__port_http }}"

    - name: Gather container info
      community.docker.docker_container_info:
        name: "{{ swag__name }}"
      register: swag_container
      failed_when: false

    - name: Debug container state if not running
      block:
        - name: Get all containers (to see if name mismatch)
          ansible.builtin.command: docker ps -a
          register: docker_ps
          changed_when: false

        - name: Show all containers
          ansible.builtin.debug:
            var: docker_ps.stdout_lines

        - name: Get logs for {{ swag__name }}
          ansible.builtin.command: docker logs {{ swag__name }}
          register: docker_logs
          failed_when: false
          changed_when: false

        - name: Show logs
          ansible.builtin.debug:
            var: docker_logs.stderr_lines
      when: swag_container.container is not defined or not (swag_container.container.State.Running | default(false))

    - name: Ensure container exists
      ansible.builtin.fail:
        msg: "Container {{ swag__name }} not found"
      when: swag_container.container is not defined

    - name: Assert container is running
      ansible.builtin.assert:
        that:
          - swag_container.container.State.Running | default(false)
        fail_msg: "Container {{ swag__name }} is not running"

    - name: "Wait for SWAG HTTP port {{ swag__port_http }} to come active"
      ansible.builtin.command: >
        docker exec {{ swag__name }} curl -fsS http://127.0.0.1:80
      register: swag_http_ready
      retries: 40
      delay: 3
      until: swag_http_ready.rc == 0
      changed_when: false
